import clientPromise from "../lib/mongodb"

interface KeywordMapping {
  keyword: string
  status: "deductible" | "non-deductible"
  atoCategory: string | null
  confidenceLevel: number
  source: string
  description: string
  examples: string[]
  usageCount: number
  createdAt: Date
  updatedAt: Date
}

const comprehensiveKeywords: Omit<KeywordMapping, "createdAt" | "updatedAt" | "usageCount">[] = [
  // Car and travel expenses - DEDUCTIBLE
  {
    keyword: "uber",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Rideshare service",
    examples: [],
  },
  {
    keyword: "taxi",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Taxi service",
    examples: [],
  },
  {
    keyword: "fuel",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Vehicle fuel",
    examples: [],
  },
  {
    keyword: "petrol",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Vehicle petrol",
    examples: [],
  },
  {
    keyword: "diesel",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Vehicle diesel",
    examples: [],
  },
  {
    keyword: "parking",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Parking fees",
    examples: [],
  },
  {
    keyword: "toll",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Road tolls",
    examples: [],
  },
  {
    keyword: "flight",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 75,
    source: "system",
    description: "Air travel",
    examples: [],
  },
  {
    keyword: "jetstar",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Airline",
    examples: [],
  },
  {
    keyword: "qantas",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Airline",
    examples: [],
  },
  {
    keyword: "virgin",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Virgin Australia airline",
    examples: [],
  },
  {
    keyword: "hotel",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 70,
    source: "system",
    description: "Accommodation",
    examples: [],
  },
  {
    keyword: "accommodation",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 75,
    source: "system",
    description: "Travel accommodation",
    examples: [],
  },
  {
    keyword: "train",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Rail transport",
    examples: [],
  },
  {
    keyword: "bus",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Bus transport",
    examples: [],
  },
  {
    keyword: "metro",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Metro transport",
    examples: [],
  },
  {
    keyword: "opal",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Sydney public transport",
    examples: [],
  },
  {
    keyword: "myki",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Melbourne public transport",
    examples: [],
  },
  {
    keyword: "bp",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "BP fuel station",
    examples: [],
  },
  {
    keyword: "shell",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Shell fuel station",
    examples: [],
  },
  {
    keyword: "caltex",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Caltex fuel station",
    examples: [],
  },
  {
    keyword: "ampol",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Ampol fuel station",
    examples: [],
  },
  {
    keyword: "7eleven",
    status: "deductible",
    atoCategory: "Car and travel expenses",
    confidenceLevel: 70,
    source: "system",
    description: "7-Eleven fuel",
    examples: [],
  },

  // Tools and equipment - DEDUCTIBLE
  {
    keyword: "laptop",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Computer equipment",
    examples: [],
  },
  {
    keyword: "computer",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Computer equipment",
    examples: [],
  },
  {
    keyword: "software",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 95,
    source: "system",
    description: "Software purchases",
    examples: [],
  },
  {
    keyword: "office365",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 95,
    source: "system",
    description: "Microsoft Office subscription",
    examples: [],
  },
  {
    keyword: "microsoft",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Microsoft products",
    examples: [],
  },
  {
    keyword: "adobe",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Adobe software",
    examples: [],
  },
  {
    keyword: "zoom",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Video conferencing",
    examples: [],
  },
  {
    keyword: "slack",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "Communication software",
    examples: [],
  },
  {
    keyword: "dropbox",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Cloud storage",
    examples: [],
  },
  {
    keyword: "google",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "Google services",
    examples: [],
  },
  {
    keyword: "apple",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Apple products",
    examples: [],
  },
  {
    keyword: "iphone",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 75,
    source: "system",
    description: "iPhone device",
    examples: [],
  },
  {
    keyword: "ipad",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "iPad device",
    examples: [],
  },
  {
    keyword: "macbook",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 90,
    source: "system",
    description: "MacBook laptop",
    examples: [],
  },
  {
    keyword: "printer",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Printer equipment",
    examples: [],
  },
  {
    keyword: "scanner",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Scanner equipment",
    examples: [],
  },
  {
    keyword: "monitor",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Computer monitor",
    examples: [],
  },
  {
    keyword: "keyboard",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "Computer keyboard",
    examples: [],
  },
  {
    keyword: "mouse",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "Computer mouse",
    examples: [],
  },
  {
    keyword: "headphones",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 75,
    source: "system",
    description: "Audio equipment",
    examples: [],
  },
  {
    keyword: "webcam",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Video equipment",
    examples: [],
  },
  {
    keyword: "officeworks",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 85,
    source: "system",
    description: "Office supplies store",
    examples: [],
  },
  {
    keyword: "jb",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "JB Hi-Fi electronics",
    examples: [],
  },
  {
    keyword: "harvey",
    status: "deductible",
    atoCategory: "Tools and equipment",
    confidenceLevel: 80,
    source: "system",
    description: "Harvey Norman electronics",
    examples: [],
  },

  // Clothing, laundry and dry-cleaning - DEDUCTIBLE
  {
    keyword: "uniform",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 95,
    source: "system",
    description: "Work uniform",
    examples: [],
  },
  {
    keyword: "safety",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 90,
    source: "system",
    description: "Safety clothing",
    examples: [],
  },
  {
    keyword: "boots",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 80,
    source: "system",
    description: "Work boots",
    examples: [],
  },
  {
    keyword: "helmet",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 90,
    source: "system",
    description: "Safety helmet",
    examples: [],
  },
  {
    keyword: "gloves",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 85,
    source: "system",
    description: "Work gloves",
    examples: [],
  },
  {
    keyword: "vest",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 85,
    source: "system",
    description: "Safety vest",
    examples: [],
  },
  {
    keyword: "laundry",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 80,
    source: "system",
    description: "Laundry services",
    examples: [],
  },
  {
    keyword: "drycleaning",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 85,
    source: "system",
    description: "Dry cleaning services",
    examples: [],
  },
  {
    keyword: "cleaning",
    status: "deductible",
    atoCategory: "Clothing, laundry and dry-cleaning",
    confidenceLevel: 75,
    source: "system",
    description: "Cleaning services",
    examples: [],
  },

  // Self-education - DEDUCTIBLE
  {
    keyword: "course",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Educational course",
    examples: [],
  },
  {
    keyword: "training",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Professional training",
    examples: [],
  },
  {
    keyword: "conference",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Professional conference",
    examples: [],
  },
  {
    keyword: "seminar",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Professional seminar",
    examples: [],
  },
  {
    keyword: "workshop",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Professional workshop",
    examples: [],
  },
  {
    keyword: "certification",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 95,
    source: "system",
    description: "Professional certification",
    examples: [],
  },
  {
    keyword: "book",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 75,
    source: "system",
    description: "Educational books",
    examples: [],
  },
  {
    keyword: "textbook",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Educational textbooks",
    examples: [],
  },
  {
    keyword: "udemy",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Online learning platform",
    examples: [],
  },
  {
    keyword: "coursera",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Online learning platform",
    examples: [],
  },
  {
    keyword: "linkedin",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 85,
    source: "system",
    description: "LinkedIn Learning",
    examples: [],
  },
  {
    keyword: "pluralsight",
    status: "deductible",
    atoCategory: "Self-education",
    confidenceLevel: 90,
    source: "system",
    description: "Online learning platform",
    examples: [],
  },

  // Working from home - DEDUCTIBLE
  {
    keyword: "internet",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Internet connection",
    examples: [],
  },
  {
    keyword: "phone",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Phone services",
    examples: [],
  },
  {
    keyword: "mobile",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Mobile phone services",
    examples: [],
  },
  {
    keyword: "electricity",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 70,
    source: "system",
    description: "Electricity bills",
    examples: [],
  },
  {
    keyword: "gas",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 70,
    source: "system",
    description: "Gas bills",
    examples: [],
  },
  {
    keyword: "heating",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 75,
    source: "system",
    description: "Heating costs",
    examples: [],
  },
  {
    keyword: "cooling",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 75,
    source: "system",
    description: "Cooling costs",
    examples: [],
  },
  {
    keyword: "desk",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Office desk",
    examples: [],
  },
  {
    keyword: "chair",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Office chair",
    examples: [],
  },
  {
    keyword: "stationery",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Office stationery",
    examples: [],
  },
  {
    keyword: "paper",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Office paper",
    examples: [],
  },
  {
    keyword: "ink",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Printer ink",
    examples: [],
  },
  {
    keyword: "toner",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 85,
    source: "system",
    description: "Printer toner",
    examples: [],
  },
  {
    keyword: "telstra",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Telstra services",
    examples: [],
  },
  {
    keyword: "optus",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Optus services",
    examples: [],
  },
  {
    keyword: "vodafone",
    status: "deductible",
    atoCategory: "Working from home",
    confidenceLevel: 80,
    source: "system",
    description: "Vodafone services",
    examples: [],
  },

  // Other work-related expenses - DEDUCTIBLE
  {
    keyword: "accountant",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 95,
    source: "system",
    description: "Accounting services",
    examples: [],
  },
  {
    keyword: "lawyer",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Legal services",
    examples: [],
  },
  {
    keyword: "consultant",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Consulting services",
    examples: [],
  },
  {
    keyword: "membership",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Professional membership",
    examples: [],
  },
  {
    keyword: "subscription",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Professional subscription",
    examples: [],
  },
  {
    keyword: "license",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Professional license",
    examples: [],
  },
  {
    keyword: "registration",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Professional registration",
    examples: [],
  },
  {
    keyword: "insurance",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Professional insurance",
    examples: [],
  },
  {
    keyword: "union",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 95,
    source: "system",
    description: "Union fees",
    examples: [],
  },
  {
    keyword: "association",
    status: "deductible",
    atoCategory: "Other work-related expenses",
    confidenceLevel: 90,
    source: "system",
    description: "Professional association",
    examples: [],
  },

  // Gifts and donations - DEDUCTIBLE
  {
    keyword: "donation",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "Charitable donation",
    examples: [],
  },
  {
    keyword: "charity",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "Charitable organization",
    examples: [],
  },
  {
    keyword: "salvos",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "Salvation Army",
    examples: [],
  },
  {
    keyword: "redcross",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "Red Cross",
    examples: [],
  },
  {
    keyword: "oxfam",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "Oxfam charity",
    examples: [],
  },
  {
    keyword: "worldvision",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 90,
    source: "system",
    description: "World Vision",
    examples: [],
  },
  {
    keyword: "cancer",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 85,
    source: "system",
    description: "Cancer charity",
    examples: [],
  },
  {
    keyword: "heart",
    status: "deductible",
    atoCategory: "Gifts and donations",
    confidenceLevel: 80,
    source: "system",
    description: "Heart foundation",
    examples: [],
  },

  // Investment-related expenses - DEDUCTIBLE
  {
    keyword: "shares",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 75,
    source: "system",
    description: "Share trading",
    examples: [],
  },
  {
    keyword: "brokerage",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 85,
    source: "system",
    description: "Brokerage fees",
    examples: [],
  },
  {
    keyword: "trading",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Trading fees",
    examples: [],
  },
  {
    keyword: "investment",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Investment fees",
    examples: [],
  },
  {
    keyword: "portfolio",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Portfolio management",
    examples: [],
  },
  {
    keyword: "financial",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 75,
    source: "system",
    description: "Financial advice",
    examples: [],
  },
  {
    keyword: "advisor",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 80,
    source: "system",
    description: "Financial advisor",
    examples: [],
  },
  {
    keyword: "commbank",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 70,
    source: "system",
    description: "CommBank investment",
    examples: [],
  },
  {
    keyword: "westpac",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 70,
    source: "system",
    description: "Westpac investment",
    examples: [],
  },
  {
    keyword: "anz",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 70,
    source: "system",
    description: "ANZ investment",
    examples: [],
  },
  {
    keyword: "nab",
    status: "deductible",
    atoCategory: "Investment-related expenses",
    confidenceLevel: 70,
    source: "system",
    description: "NAB investment",
    examples: [],
  },

  // NON-DEDUCTIBLE ITEMS
  {
    keyword: "woolworths",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Grocery shopping",
    examples: [],
  },
  {
    keyword: "coles",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Grocery shopping",
    examples: [],
  },
  {
    keyword: "aldi",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Grocery shopping",
    examples: [],
  },
  {
    keyword: "iga",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Grocery shopping",
    examples: [],
  },
  {
    keyword: "groceries",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 90,
    source: "system",
    description: "Grocery shopping",
    examples: [],
  },
  {
    keyword: "supermarket",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Supermarket shopping",
    examples: [],
  },
  {
    keyword: "netflix",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Entertainment streaming",
    examples: [],
  },
  {
    keyword: "spotify",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Music streaming",
    examples: [],
  },
  {
    keyword: "disney",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Entertainment streaming",
    examples: [],
  },
  {
    keyword: "amazon",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 70,
    source: "system",
    description: "Online shopping",
    examples: [],
  },
  {
    keyword: "ebay",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 70,
    source: "system",
    description: "Online shopping",
    examples: [],
  },
  {
    keyword: "restaurant",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 70,
    source: "system",
    description: "Personal dining",
    examples: [],
  },
  {
    keyword: "cafe",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 70,
    source: "system",
    description: "Personal dining",
    examples: [],
  },
  {
    keyword: "mcdonald",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Fast food",
    examples: [],
  },
  {
    keyword: "kfc",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Fast food",
    examples: [],
  },
  {
    keyword: "subway",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Fast food",
    examples: [],
  },
  {
    keyword: "dominos",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Fast food",
    examples: [],
  },
  {
    keyword: "pizza",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Personal food",
    examples: [],
  },
  {
    keyword: "alcohol",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Alcoholic beverages",
    examples: [],
  },
  {
    keyword: "liquor",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Alcoholic beverages",
    examples: [],
  },
  {
    keyword: "wine",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Alcoholic beverages",
    examples: [],
  },
  {
    keyword: "beer",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Alcoholic beverages",
    examples: [],
  },
  {
    keyword: "gaming",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Gaming entertainment",
    examples: [],
  },
  {
    keyword: "steam",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Gaming platform",
    examples: [],
  },
  {
    keyword: "playstation",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Gaming console",
    examples: [],
  },
  {
    keyword: "xbox",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Gaming console",
    examples: [],
  },
  {
    keyword: "nintendo",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Gaming console",
    examples: [],
  },
  {
    keyword: "gym",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Personal fitness",
    examples: [],
  },
  {
    keyword: "fitness",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Personal fitness",
    examples: [],
  },
  {
    keyword: "hairdresser",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Personal grooming",
    examples: [],
  },
  {
    keyword: "barber",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Personal grooming",
    examples: [],
  },
  {
    keyword: "beauty",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Personal beauty",
    examples: [],
  },
  {
    keyword: "spa",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Personal wellness",
    examples: [],
  },
  {
    keyword: "massage",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Personal wellness",
    examples: [],
  },
  {
    keyword: "cinema",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 85,
    source: "system",
    description: "Entertainment",
    examples: [],
  },
  {
    keyword: "movie",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Entertainment",
    examples: [],
  },
  {
    keyword: "theatre",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Entertainment",
    examples: [],
  },
  {
    keyword: "concert",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 75,
    source: "system",
    description: "Entertainment",
    examples: [],
  },
  {
    keyword: "ticketek",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Entertainment tickets",
    examples: [],
  },
  {
    keyword: "ticketmaster",
    status: "non-deductible",
    atoCategory: null,
    confidenceLevel: 80,
    source: "system",
    description: "Entertainment tickets",
    examples: [],
  },
]

async function seedKeywords() {
  try {
    console.log("🌱 Starting comprehensive keyword seeding...")

    const client = await clientPromise
    const db = client.db("taxapp")
    const collection = db.collection("keyword_mappings")

    // Create indexes for better performance
    await collection.createIndex({ keyword: 1 }, { unique: true })
    await collection.createIndex({ status: 1 })
    await collection.createIndex({ atoCategory: 1 })
    await collection.createIndex({ source: 1 })

    console.log("📊 Created database indexes")

    const now = new Date()
    const keywordsToInsert = comprehensiveKeywords.map((keyword) => ({
      ...keyword,
      usageCount: 0,
      createdAt: now,
      updatedAt: now,
    }))

    console.log(`💾 Inserting ${keywordsToInsert.length} keyword mappings...`)

    // Use insertMany with ordered: false to continue on duplicates
    const result = await collection.insertMany(keywordsToInsert, { ordered: false })

    console.log(`✅ Successfully inserted ${result.insertedCount} keyword mappings`)

    // Get statistics
    const stats = await collection
      .aggregate([
        {
          $group: {
            _id: "$status",
            count: { $sum: 1 },
          },
        },
      ])
      .toArray()

    console.log("📈 Keyword Statistics:")
    stats.forEach((stat) => {
      console.log(`  ${stat._id}: ${stat.count}`)
    })

    const categoryStats = await collection
      .aggregate([
        { $match: { status: "deductible" } },
        {
          $group: {
            _id: "$atoCategory",
            count: { $sum: 1 },
          },
        },
        { $sort: { count: -1 } },
      ])
      .toArray()

    console.log("📊 ATO Category Distribution:")
    categoryStats.forEach((stat) => {
      console.log(`  ${stat._id}: ${stat.count}`)
    })

    console.log("🎉 Keyword seeding completed successfully!")
  } catch (error: any) {
    if (error.code === 11000) {
      console.log("⚠️ Some keywords already exist (duplicates skipped)")
    } else {
      console.error("❌ Error seeding keywords:", error)
      throw error
    }
  }
}

// Run the seeding function
seedKeywords()
  .then(() => {
    console.log("✅ Seeding process completed")
    process.exit(0)
  })
  .catch((error) => {
    console.error("💥 Seeding failed:", error)
    process.exit(1)
  })
